name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print multi-line
        run: |
          echo "First line"
          echo "Second line"
      - name: Pring goodbye
        run: echo "Done - bye!"
  
